### ISSUE TITLE
[1주차] Getting started

### ISSUE THREAD

**Issue by joowankim** [BackendStudyOrg/python_concepts#1]
아래 사항들을 조사하고 공부한 내용을 공유해주세요.

1. PEP 8 스타일 가이드
2. Python 개발환경 설정하기
3. Python 인터프리터 동작방식

**Comment by ghost** [comment]
1. PEP 8 (내용이 많아서 읽으면서 작성했습니다)  - https://www.notion.so/PEP-8-c14205201f50407799a4e0d7c9845162 
2. https://www.notion.so/fbdfe13fbcca428f9d14095f67f1689a
3. https://www.notion.so/Python-b29aa801dc11441c89ac84c53d2c2909

**Comment by chldppwls12** [comment]
1. https://velog.io/@chldppwls12/PEP-8-%EC%8A%A4%ED%83%80%EC%9D%BC-%EA%B0%80%EC%9D%B4%EB%93%9C
2. https://velog.io/@chldppwls12/python-%EA%B0%9C%EB%B0%9C%ED%99%98%EA%B2%BD-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0
3. https://velog.io/@chldppwls12/python-%EB%8F%99%EC%9E%91-%EB%B0%A9%EC%8B%9D

**Comment by hjhjhj00** [comment]
https://www.notion.so/django-study-1-0f0a181c2549489fa8715fb518978d9f

**Comment by hjhjhj00** [comment]
https://www.notion.so/django-study-1-0f0a181c2549489fa8715fb518978d9f
