### ISSUE TITLE
[2주차] 리스트와 딕셔너리

### ISSUE THREAD

**Issue by joowankim** [BackendStudyOrg/python_concepts#2]
파이썬의 자료구조 리스트와 딕셔너리에 대해 학습하세요.

1. 리스트
    - 슬라이싱
    - 스트라이드
    - 언패킹
2. 딕셔너리
    - 초기화
    - setdefault vs defaultdict
    - `__missing__`
3. 컴프리헨션
4. enumerate
5. zip

반드시 위에 것만 할 필요는 없습니다.
필요하다면 더 공부하고 그것까지도 정리해주세요.
정리는 언제나 자신이 나중에 그 글을 다시 봤을 때도 짧은 시간안에 이해를 할 수 있을 정도로 자세하게 하는게 가장 좋습니다.

**Comment by ghost** [comment]
1. https://www.notion.so/2-1-list-c19ca3a9a6a345f7aa0d30d7dd382d66
2. https://www.notion.so/2-2-Dictionary-b0c5fd6354c44f37a59c9b0ae7df6489
3. https://www.notion.so/2-3-1-comprehension-cb8d1184468f4332892d9d2568804b4d
4. https://www.notion.so/2-4-enumerate-069385a1e7d640d4ac83bc0c9b77b532
5. https://www.notion.so/2-5-zip-7e85069b913f4b199541a52a766fff4d


### Comment
1. 리스트
    - 균일 시퀀스, 컨테이너 시퀀스 언급 좋았음
    - 슬라이싱
        - ≤ x < → 이유 및 장점을 정리한 것 좋았음
2. 딕셔너리
    - setdefault vs defaultdict
        - 존재하지 않는 키 k 로 d[k] 를 접근하면 dict는 오류를 발생시킨다. → KeyError
    - `__missing__`
        - `setdefault` 와 `defaultdict` 가 처리하기 애매한 문제를 처리할 수 있다.
3. 컴프리헨션
    - generator expression 언급 좋았음

**Comment by chldppwls12** [comment]
1. https://velog.io/@chldppwls12/Python-%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EB%A6%AC%EC%8A%A4%ED%8A%B8-%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1
https://velog.io/@chldppwls12/Python-packing-unpacking-mpwe4ifv
2. https://velog.io/@chldppwls12/Python-%EB%94%95%EC%85%94%EB%84%88%EB%A6%AC%EC%99%80-%EA%B4%80%EB%A0%A8-%ED%95%A8%EC%88%98
3. https://velog.io/@chldppwls12/Python-%ED%8C%8C%EC%9D%B4%EC%8D%AC-Comprehension
4-5. https://velog.io/@chldppwls12/Python-enumerate-zip

### Comment

1. 리스트
    - 얕은 복사, 깊은 복사
        - `id()` 를 활용하면 주소값을 비교할 수 있다.
    - 스트라이드
        - better way 정리한 것 좋았음
2. 딕셔너리
    - 초기화
        - `dict` 형의 메소드 사용법 정리 좋았음
3. 컴프리헨션
    - iterable과 iterator에 대한 정리가 좋았음
4. zip
    - unzip 언급 좋았음
