### ISSUE TITLE
[3주차] 함수

### ISSUE THREAD

**Issue by joowankim** [BackendStudyOrg/python_concepts#3]
1. 함수 선언하기
2. 람다식
3. 일급 객체
4. Namespace와 Closure
5. 제네레이터

**Comment by ghost** [comment]
1. https://www.notion.so/3-1-3a9e4b2e01c44208867a45ed86b00d23
2. https://www.notion.so/3-2-lambda-function-b29693735a1f430aab1caa6ac3643bfa
3. https://www.notion.so/3-3-First-class-citizen-250b054670744479af9095deeaa40204
4. https://www.notion.so/3-4-Namespace-Closure-ec313c9f105a496d905d164d2f916239
5. https://www.notion.so/3-5-generator-9c3b936d77394e518a7bbd3e7c01e3c4

**Comment by chldppwls12** [comment]
1. https://velog.io/@chldppwls12/Python-%ED%95%A8%EC%88%98-%EC%84%A0%EC%96%B8%ED%95%98%EA%B8%B0
2. https://velog.io/@chldppwls12/Python-%EB%9E%8C%EB%8B%A4-%ED%91%9C%ED%98%84%EC%8B%9D-lambda-expression
3. https://velog.io/@chldppwls12/Python-%EC%9D%BC%EA%B8%89-%EA%B0%9D%EC%B2%B4first-class-object
4.  1) https://velog.io/@chldppwls12/Python-%EB%84%A4%EC%9E%84%EC%8A%A4%ED%8E%98%EC%9D%B4%EC%8A%A4
     2) https://velog.io/@chldppwls12/Python-%ED%81%B4%EB%A1%9C%EC%A0%80closure-r5dsnnrd
5. https://velog.io/@chldppwls12/Python-%EC%A0%9C%EB%84%A4%EB%A0%88%EC%9D%B4%ED%84%B0-generator
