### ISSUE TITLE
[4주차] 클래스

### ISSUE THREAD

**Issue by joowankim** [BackendStudyOrg/python_concepts#4]
1. 클래스를 정의하는 방법
2. 메타 클래스
2. 클래스 속성 vs 객체 속성
3. `Callable`과 `__call__`
4. `@dataclass`
5. 인스턴스 메소드, 클래스 메소드, 스태틱 메소드
6. 단일 상속, 다중 상속, 믹스인
7. `super` 클래스

**Comment by ghost** [comment]
1. https://www.notion.so/4-1-aaf812741eb040099d45a55cc56ad849
2. https://www.notion.so/4-2-61c0c838d31c48fea3c12ea192f89cde
3. https://www.notion.so/4-3-vs-88b75b28bd4442bd889a25ce655a4b2a
4. https://www.notion.so/4-4-callable-__call__-abac49d5ebde4119a0e649094eb9bf8c
5. https://www.notion.so/4-5-dataclass-a7bfec748c3f40738cb946dd9ee655f2
6. https://www.notion.so/4-6-3acb7dbdd05d41228a92eb63e374548e
7. https://www.notion.so/4-7-940e0c95c6184ba9a82921ddfaba8ee4
8. https://www.notion.so/4-8-super-52bc85531ba947a79e40fd77532de242

**Comment by chldppwls12** [comment]
1. https://velog.io/@chldppwls12/Python-%ED%81%B4%EB%9E%98%EC%8A%A4Class-%EB%A7%8C%EB%93%A4%EA%B8%B0
2. https://velog.io/@chldppwls12/Python-%EB%A9%94%ED%83%80-%ED%81%B4%EB%9E%98%EC%8A%A4metaclass
3. https://velog.io/@chldppwls12/Python-%ED%81%B4%EB%9E%98%EC%8A%A4-%EC%86%8D%EC%84%B1%EA%B3%BC-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4-%EC%86%8D%EC%84%B1
6. https://velog.io/@chldppwls12/Python-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4-%EB%A9%94%EC%86%8C%EB%93%9C-%ED%81%B4%EB%9E%98%EC%8A%A4-%EB%A9%94%EC%86%8C%EB%93%9C-%EC%8A%A4%ED%83%9C%ED%8B%B1-%EB%A9%94%EC%86%8C%EB%93%9C
7 (단일상속, 다중상속). https://velog.io/@chldppwls12/Python-%EC%83%81%EC%86%8DInheritance%EC%98%A4%EB%B2%84%EB%9D%BC%EC%9D%B4%EB%94%A9Overriding
7 (믹스인). https://velog.io/@chldppwls12/Python-%EB%AF%B9%EC%8A%A4%EC%9D%B8Mixin%EA%B3%BC-%EC%BB%B4%ED%8F%AC%EC%A7%80%EC%85%98Composition
